<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="69" started-at="2017-01-31T03:59:26Z" finished-at="2017-01-31T03:59:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="69" started-at="2017-01-31T03:59:26Z" finished-at="2017-01-31T03:59:26Z">
      <class name="com.sqa.im.helpers.DataHelperTest">
        <test-method status="FAIL" signature="testDataHelper()[pri:0, instance:com.sqa.im.helpers.DataHelperTest@170798fd]" name="testDataHelper" duration-ms="23" started-at="2017-01-30T19:59:26Z" finished-at="2017-01-30T19:59:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[does not work correctly expected [
3	5	4	1
3.1	5.55	4.1	1.3
 3 5	4	1
3 5	4	1
	]] but found [3	5	4	1	3.1	5.55	4.1	1.3	3	5	4	1	3	5	4	1	]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: does not work correctly expected [
3	5	4	1
3.1	5.55	4.1	1.3
 3 5	4	1
3 5	4	1
	]] but found [3	5	4	1	3.1	5.55	4.1	1.3	3	5	4	1	3	5	4	1	]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.sqa.im.helpers.DataHelperTest.testDataHelper(DataHelperTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDataHelper -->
      </class> <!-- com.sqa.im.helpers.DataHelperTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
